### ISSUE TITLE
Unpacking source package 3.14.0 gives strange message.

### ISSUE THREAD

**Issue by hyoklee** [OPENDAP/bes#1]
I get the following messages on CentOS:

```
tar: Ignoring unknown extended header keyword `SCHILY.dev`
tar: Ignoring unknown extended header keyword `SCHILY.ino`
tar: Ignoring unknown extended header keyword `SCHILY.nlink`
```

I think the source package is made from Mac OS X and causes the above output.

**Comment by jgallagher59701** [comment]
> On May 11, 2015, at 1:08 PM, H. Joe Lee <notifications@github.com> wrote:
> 
> I get the following messages on CentOS:
> 
> tar: Ignoring unknown extended header keyword `SCHILY.dev`
> tar: Ignoring unknown extended header keyword `SCHILY.ino`
> tar: Ignoring unknown extended header keyword `SCHILY.nlink`
> I think the source package is made from Mac OS X and causes the above output.
> 
> 
Unpacking it on what OS?

James'
> —
> Reply to this email directly or view it on GitHub <https://github.com/OPENDAP/bes/issues/1>.
> 

--
James Gallagher
jgallagher at opendap.org
406.723.8663

**Comment by hyoklee** [comment]
Linux (CentOS 6&7)

**Comment by hyoklee** [comment]
I downloaded sources from here:

http://opendap.org/download/hyrax/1.11#downloads

**Comment by jgallagher59701** [comment]
I'm not sure how this was resolved
