### ISSUE TITLE
DMR XML  generates invalid type for attribute.

### ISSUE THREAD

**Issue by hyoklee** [OPENDAP/bes#12]
In [1], you can see

```
    DATA_GRANULE_PR_CAL_COEF {
        Float32 Vdata_field_transCoef -0.5199999809;
```

For the above attribute in [2], you will get
```
   <Attribute name="DATA_GRANULE_PR_CAL_COEF" type="Container">
        <Attribute name="Vdata_field_transCoef" type="Byte">
            <Value>-0.5199999809</Value>
        </Attribute>
```

The type should be "Float32", not "Byte".

[1] https://eosdap.hdfgroup.org:8080/opendap/data/NASAFILES/hdf4/1B21_CSI.990906.10217.KORA.6.HDF.das

[2] https://eosdap.hdfgroup.org:8080/opendap/data/NASAFILES/hdf4/1B21_CSI.990906.10217.KORA.6.HDF.dmr.xml

**Comment by ndp-opendap** [comment]
I think this is something for James, not me.

**Comment by jgallagher59701** [comment]
Joe, is this in the handler or in libdap?

**Comment by hyoklee** [comment]
I have no clue. I’ll CC to Kent. DAS output is correct so I suspected it’s libdap4 or bes.

**Comment by kyang2014** [comment]
I agree with Joe.  The HDF4 handler  CF simply transits the DAP2 output to DAP4 following http://docs.opendap.org/index.php/Making_the_transition_to_DAP4
The only function the handler called is dmr->build_using_dds(dds) based on the DDS and DAS Joe points out. If DAS and DDS are right, something must be wrong with the  build_using_dds
Function.

Kent

**Comment by jgallagher59701** [comment]
On November 12, 2015 at 12:51:25 PM, kyang2014 (notifications@github.com) wrote:

I agree with Joe. The HDF4 handler CF simply transits the DAP2 output to DAP4 following http://docs.opendap.org/index.php/Making_the_transition_to_DAP4
The only function the handler called is dmr->build_using_dds(dds) based on the DDS and DAS Joe points out. If DAS and DDS are right, something must be wrong with the build_using_dds
Function.
Ah, So this is a DAP4 issue?



Kent

**Comment by kyang2014** [comment]
I think so.

**Comment by jgallagher59701** [comment]
Fixed. The wrong constant was used in D4Attributes.cc. Pushed to libdap master
