### ISSUE TITLE
Cannot install experimental bes .deb package from Hyrax 1.11 release (Ubuntu 14.04)

### ISSUE THREAD

**Issue by michaeljb** [OPENDAP/bes#2]
I downloaded `bes_3.14.0-2.NASA_x86_64.deb` from [OPeNDAP's experimental debian package index](http://www.opendap.org/pub/binary/hyrax-1.11/ubuntu14/), but ran into a dependency issue when trying to install it with `gdebi`. Apparently it requires the package `libbz2`, which is not available in the default repos for Ubuntu 14.04 (Trusty Tahr).

There is, however, a package named [`libbz2-1.0`](http://packages.ubuntu.com/trusty/libbz2-1.0) available for Trusty Tahr; maybe the dependency could be changed to this in the published .deb?

Below is my output showing the failed installation:

```
~$ sudo gdebi bes_3.14.0-2.NASA_x86_64.deb
Reading package lists... Done
Building dependency tree
Reading state information... Done
Building data structures... Done
Building data structures... Done
This package is uninstallable
Dependency is not satisfiable: libbz2
```

The development package, `bes-devel_3.14.0-2.NASA_x86_64.deb`, installed without issue.

**Comment by michaeljb** [comment]
See also https://github.com/OPENDAP/libdap4/issues/2

**Comment by michaeljb** [comment]
System info:

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04 LTS
Release:        14.04
Codename:       trusty
~$ uname -a
Linux vtelemark 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jgallagher59701** [comment]
I think we need to retrace our steps and look at a different way to build deb packages.
