### ISSUE TITLE
NdArray not 1-D in covjson response from Hyrax

### ISSUE THREAD

**Issue by ffang10** [OPENDAP/bes#244]
According to the specification:

https://covjson.org/spec/#ndarray-objects

an NdArray shall be one-dimensional.

This is not true in the current covjson response in Hyrax. For example:

https://snpp-omps.gesdisc.eosdis.nasa.gov/opendap/SNPP_OMPS_Level3/OMPS_NPP_NMTO3_L3_DAILY.2/2012/OMPS-NPP_NMTO3-L3-DAILY_v2.1_2012m0126_2017m0227t060834.h5.covjson?ColumnAmountO3[140:1:150][35:1:45],Latitude[140:1:150],Longitude[35:1:45]

shows a 2-D array for range "ColumnAmountO3", although the JSON files shows it is an NdArray type.

**Comment by lewismc** [comment]
Here's the CovJSON for those that cannot access it.

[OMPS-NPP_NMTO3-L3-DAILY_v2.1_2012m0126_2017m0227t060834.h5.covjson.zip](https://github.com/OPENDAP/bes/files/3020046/OMPS-NPP_NMTO3-L3-DAILY_v2.1_2012m0126_2017m0227t060834.h5.covjson.zip)

**Comment by lewismc** [comment]
I think I've narrowed this issues down to [line 1153 of FoDapCovJsonTransform.cc](https://github.com/OPENDAP/bes/blob/master/modules/fileout_covjson/FoDapCovJsonTransform.cc#L1153) within the _**printRangesWorker**_ method where the actual parameter range values are written.

**Comment by lewismc** [comment]
@hemphilc if you are able to take a look at this it would be greatly appreciated. Thanks in advance.

**Comment by hemphilc** [comment]
@lewismc 

I see there are a couple issues open against the CovJSON module at the moment. Now that I finished my bachelor's as of last week, I will finally have some time to work on the module. I'll start looking into this issue and the other issues ASAP.

**Comment by lewismc** [comment]
Nice thanks @hemphilc were getting some good uptake right now.

**Comment by hemphilc** [comment]
I believe I have resolved this issue in PR #312 

NdArray will now output as one-dimensional.

**Comment by ffang10** [comment]
Would this be in Hyrax 1.16.1 or 1.16.2?
