### ISSUE TITLE
Is the 'CoverageCollection' a misinterpretation of NASA data in the covjson response in Hyrax

### ISSUE THREAD

**Issue by ffang10** [OPENDAP/bes#245]
In our test server of Hyrax 1.15.1, if I request a covjson file for a granule, most returns as 'CoverageCollection'. Some of these are globally gridded data with multiple observations (arrays) sharing a single pair of latitude and longitude coordinates. For example

https://snpp-omps.gesdisc.eosdis.nasa.gov/opendap/SNPP_OMPS_Level3/OMPS_NPP_NMTO3_L3_DAILY.2/2012/OMPS-NPP_NMTO3-L3-DAILY_v2.1_2012m0126_2017m0227t060834.h5.covjson

Should the granule be interpreted as a 'Coverage' or a 'CoverageCollection'?

**Comment by lewismc** [comment]
> Should the granule be interpreted as a 'Coverage' or a 'CoverageCollection'?

I am honestly not sure... the CovJSON specification doesn't make this crystal clear (if it does then I am missing it)

What I have found is the following. The `printCoverageHeaderWorker` method writes out whether this is a Coverage or CoverageCollection. If you look at the comment on [lines 1248-1249 of FoDapCovJsonTransform.cc](https://github.com/OPENDAP/bes/blob/master/modules/fileout_covjson/FoDapCovJsonTransform.cc#L1248-L1249) you see
> If we have more than one parameter, we are dealing with a Coverage Collection, so we must print accordingly

...likewise if you look at the comment on [lines 1272-1273 of FoDapCovJsonTransform.cc](https://github.com/OPENDAP/bes/blob/master/modules/fileout_covjson/FoDapCovJsonTransform.cc#L1272-L1273) you see the following
> If we have a single parameter, or even no parameters, we will print as a "normal" coverage

Based on the comments in the source code, the behavhiour is correct, however @jonblower can you please confirm?

**Comment by jonblower** [comment]
> Should the granule be interpreted as a 'Coverage' or a 'CoverageCollection'?

A Coverage has a *single* domain but can have 1..* ranges (i.e. data arrays). So you can record many variables in the same Coverage, as long as they have the same domain (i.e. the items in the data arrays map to the same points in space/time). I haven't looked at the link above (I don't have a login) but I suspect that you have a single Coverage.

A CoverageCollection is just a collection of Coverages, but they can share some metadata (e.g. the type of the domain).

This probably does need to be made clearer in the CovJSON spec, but I would say that if you have a single domain then you have a single Coverage. There is nothing stopping you from recording each variable in a separate Coverage if you want and putting them in a Collection.

If you can post the CovJSON in a way that doesn't require a separate login I can have a closer look.

**Comment by hemphilc** [comment]
I think this issue can be closed. The fileout_covjson module no longer supports outputting Coverage Collections. From my understanding, a DDS will only ever provide a single Coverage dataset, so there is no need to support Coverage Collection printing.

**Comment by ffang10** [comment]
For some reason I haven't gotten the updates since opening the ticket. Reading the last comment does it mean that the fileout_covjson is outputting the correct 'Coverage' info instead of 'CoverageCollection'? Which Hyrax version does this fix go in?
