### ISSUE TITLE
server bind address configuration option

### ISSUE THREAD

**Issue by mcenirm** [OPENDAP/bes#3]
Please add a way to specify an address (in particular, "127.0.0.1") to which bes's server port should bind.

cf `ServerApp::run()` in `server/ServerApp.cc`

**Comment by jgallagher59701** [comment]
> On Aug 9, 2015, at 1:30 PM, Michael McEniry <notifications@github.com> wrote:
> 
> Please add a way to specify an address (in particular, "127.0.0.1") to which bes's server port should bind.
> 
> cf ServerApp::run() in server/ServerApp.cc
> 
> 
Added to Jira.

James
> —
> Reply to this email directly or view it on GitHub <https://github.com/OPENDAP/bes/issues/3>.
> 

--
James Gallagher
jgallagher at opendap.org
406.723.8663
