### ISSUE TITLE
how to read files saved in hadoop

### ISSUE THREAD

**Issue by morix-gao** [OPENDAP/bes#305]
I want to put NetCDF files to hadoop, how to read it by BES? How to Configure bes or modify it?
Thank U～

**Comment by jgallagher59701** [comment]
> On Dec 25, 2019, at 2:36 AM, morix-gao <notifications@github.com> wrote:
> 
> I want to put NetCDF files to hadoop, how to read it by BES? How to Configure bes or modify it?

I think the best way now to do that is to turn the BES into a lambda function using a dockerized BES. It’s not a trivial project, but one that wold be very interesting.


> Thank U～
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 

--
James Gallagher
jgallagher@opendap.org

**Comment by morix-gao** [comment]
> On Dec 25, 2019, at 2:36 AM, morix-gao ***@***.***> wrote: I want to put NetCDF files to hadoop, how to read it by BES? How to Configure bes or modify it?
> I think the best way now to do that is to turn the BES into a lambda function using a dockerized BES. It’s not a trivial project, but one that wold be very interesting.
> […](#)
> Thank U～ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
> -- James Gallagher jgallagher@opendap.org

Thank U!

**Comment by ndp-opendap** [comment]
We do already produce a dockerized BES:

https://hub.docker.com/r/opendap/besd

You may find that a starting point. The Docker files are in our GitHub repo here:

https://github.com/OPENDAP/hyrax-docker/
