### ISSUE TITLE
Zarr support

### ISSUE THREAD

**Issue by fbriol** [OPENDAP/bes#356]
Hello, do you have a plan to develop a module to read Zarr files with N5?

I've started looking at the code, but I can't see if the work required seems huge or not. If I want to try to develop it, which module should I use as an example? NetCDF? Thanks for your help.

**Comment by ndp-opendap** [comment]
Hi Frédéric,

I think it should be fairly straight forward. You probably want to work with the dmrpp_module as what that code does is very similar to Zarr. That module can read dmr++ files (which are not much different than Zarr, at least in information content) and retrieves data values using range GET calls.  

In fact the most effective thing might be to write something that makes a dmr++ file from a Zarr file as an initial step. Then, using what was learned, one might write code to read the Zarr file and build an instance of the dmr++ object in memory and let the BES machinery handle the rest.

Please feel free to ask questions and I'll try to help you understand things as needed.

Sincerely,

Nathan

**Comment by jgallagher59701** [comment]
I'm going to close this issue. Kodi Neumiller looked in to this and modulo updating the decompression code, the DMR++ module of the BES can read any Zarr file.
