### ISSUE TITLE
'Phony_dim' in .nc4 downloads of 3IMERGM data from Hyrax 1.13.3

### ISSUE THREAD

**Issue by ffang10** [OPENDAP/bes#38]
Although the (HDF5) handler in Hyrax 1.13.3 correctly presents the dimensions, a .nc4 download changes them to 'phony_dim_' in download file - this is in fact observed in other data like Merra2 as well. The 3IMERGM data is located here:

https://gpm1.gesdisc.eosdis.nasa.gov/data/s4pa/GPM_L3/GPM_3IMERGM.03/

The other issue with 3IMERG is that an 'nc_' is prepended to the download filename, a very undesirable feature to us. I recognize that both issues could be related to the netcdf library.

**Comment by ndp-opendap** [comment]
I don't know much about the _phony_dim_ in the fileout_netcdf response. I'll have to look at that.

I do know that the "nc_" prefix has something to do with the netCDF library not supporting file names that begin with a number. This limitation may be old and the sever could change this behavior. Again, I'll have to see.

**Comment by ffang10** [comment]
Thanks Nathan. Yes prepending ‘nc_’ is likely a netcdf library behavior. In some of the (earlier) releases this behavior wasn’t there, or at least got suppressed. We built our secondary services on top of it. The non-uniform name change would affect those services to such a level that we probably can never upgrade Hyrax servers where such data is served. I wonder if netcdf people should be alerted, or at least provide an option to suppress this behavior.

-Fan

**Comment by ndp-opendap** [comment]
Let me clarify: In the case of prepending "nc_" to file names that begin with a digit: Hyrax is doing that. And it;s doing that because, at one time, if Hyrax returned a netCDF file whose name began with a digit the file was unusable by the down stream client tools.

**Comment by ffang10** [comment]
Can we provide a BES key to suppress that in that case?

**Comment by ndp-opendap** [comment]
Fan,

**Short Answer**: Yes,  although it's an OLFS thing so the config parameter would be added to _olfs.xml_
**Longer Answer**:. Before we make this change I think we should examine the roots of the prefixing behavior. If the conditions that required the prefix are no longer operational in the client software base then I think it is reasonable to simply remove the behavior from the server rather than increasing the configuration complexity.

N

**Comment by ffang10** [comment]
I don't see this in 1.10.1 server, so suspect it is a library issue. We can trying compiling the fileout netcdf module with whatever netcdf library it was compiled with for 1.10.1 to see if the problem goes away.

**Comment by ffang10** [comment]
My previous post concerns the "phony_dim" issue. I realized that this thread also discussed the issue prepending "nc_" to filenames starting with a digit, which impacted our TRMM and GPM data. Both are critical issues for us.

**Comment by kyang2014** [comment]
This is a file netCDF module issue since the HDF5 handler correctly generates the dimension names.

**Comment by ndp-opendap** [comment]
These issues have been fixed in Hyrax-1.13.4 release
