### ISSUE TITLE
roi() etc. server-side functions shall not prepend to variable and attribute names

### ISSUE THREAD

**Issue by ffang10** [OPENDAP/bes#40]
At the moment (as of 1.13.3) using server-side functions can result in modified variable and attribute names. For instance the following CDL snippet after running roi() with a fileout netcdf response. This breaks the other-wise CF-compliance of data coming out of BES.  Prepending strings like "row_subset." is not desired.

float roi_subset.Latitude(FakeDim0, nXtrack) ;
		roi_subset.Latitude:_FillValue = -1.267651e+30f ;
		roi_subset.Latitude:missing_value = -1.267651e+30f ;
		roi_subset.Latitude:scale_factor = 1. ;
		roi_subset.Latitude:add_offset = 0. ;
		roi_subset.Latitude:title = "Latitude of the center of the groundpixel" ;
		roi_subset.Latitude:units = "degrees_north" ;
		roi_subset.Latitude:UniqueFieldDefinition = "Aura-Shared" ;
		roi_subset.Latitude:origname = "Latitude" ;
		roi_subset.Latitude:fullnamepath = "/HDFEOS/SWATHS/ColumnAmountNO2/Geolocation Fields/Latitude" ;

**Comment by jgallagher59701** [comment]
I'll add this to Jira. My guess is that this is an artifact of the way that the Region Of Interest function packages it's result (in a structure) and the way that variable is 'flattened' by the code that 'unrolls' the result from the function evaluator.

**Comment by ndp-opendap** [comment]
This is fixed in Hyrax-1.13.4 release
