### ISSUE TITLE
Email icon at top of pages goes to the Mailing list instead of to an OPeNDAP email address

### ISSUE THREAD

**Issue by Arika-V** [OPENDAP/bes#926]
The mail sign at the top of the pages goes to the OPeNDAP mailing list (https://groups.google.com/a/opendap.org/g/opendap). Typically, I think that's the sign for writing an email to the org (e.g., support@opendap.com)? So it's a little confusing. I would suggest either A) changing that icon to represent a mailing list or B) changing the link to be support@

![Image](https://github.com/OPENDAP/bes/assets/170548569/da3d3a05-d7ce-4243-8a2b-ceb569c0a810)

**Comment by Arika-V** [comment]
(noting the template) Here's the url where this issue was found: https://newopendap.flywheelsites.com/

**Comment by Mikejmnez** [comment]
Hi @Arika-V 

This is an unrelated repository to the website. I am going to close this. For now, when creating an item on the website Project, we should not attach it to an existing repository . This means leaving it as `Draft`.
